Repository Za-DO/Semo, pull requests merged in 2022-10, with the labels that each got.

#96 [2022.10.03]feat/addToSingingList >> 노래 추가할때 SingingList생성 및 SingingList에 노래 추가되게 구현
  Semo/Views/AddSong/AddSingingListTagView.swift
Labels: ✨ Feature

#100 [2022.10.03] feat/icon >> 앱 아이콘 추가 및 이름 변경
  Semo.xcodeproj/project.pbxproj
  Semo/Assets.xcassets/AppIcon.appiconset/1024.png
  Semo/Assets.xcassets/AppIcon.appiconset/114.png
  Semo/Assets.xcassets/AppIcon.appiconset/120.png
  Semo/Assets.xcassets/AppIcon.appiconset/180.png
  Semo/Assets.xcassets/AppIcon.appiconset/29.png
  Semo/Assets.xcassets/AppIcon.appiconset/40.png
  Semo/Assets.xcassets/AppIcon.appiconset/57.png
  Semo/Assets.xcassets/AppIcon.appiconset/58.png
  Semo/Assets.xcassets/AppIcon.appiconset/60.png
  Semo/Assets.xcassets/AppIcon.appiconset/80.png
  Semo/Assets.xcassets/AppIcon.appiconset/87.png
  Semo/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: ✨ Feature

#101 [2022.10.03] feat/MakeSongBadge >> gender, tune 태그 칩 추가, genderItem 텍스트 수정
  Semo.xcodeproj/project.pbxproj
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/SongDetail/SongDetailView.swift
Labels: ✨ Feature

#105 [2022.10.03] Bugfix/main view fetch >> 메인뷰 및 싱잉리스트 리프레쉬 버그 수정
  Semo/Managers/CoreDataManager.swift
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingList/SingingListView.swift
  Semo/Views/SingingListDetail/SingingListDetailCellView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
Labels: :lady_beetle: Bug

#111 [2022.10.04] hotfix/main >> 메인 뷰 깨지는거 수정
  Semo/Views/MainView.swift
Labels: :lady_beetle: Bug

#109 [2022.10.04] feat/changeSingingListTitle >> 싱잉리스트 디테일 뷰 패딩값 조절 및 alert 기능 삭제
  Semo.xcodeproj/xcuserdata/jungin-yoo.xcuserdatad/xcschemes/xcschememanagement.plist
  Semo/Views/SingingListDetail/SingingListDetailView.swift
Labels: ✨ Feature

#112 [2022.10.04] feat/AdjustSizeAsDevice >> 기기대응을 위한 익스텐션 추가
  Semo.xcodeproj/project.pbxproj
  Semo/Extensions/UIScreenViewExtension.swift
  Semo/Views/OnBoarding/OnBoardingView.swift
Labels: ✨ Feature

#113 [2022.10.04] feat/coredata >> 싱잉리스트 fetch 메서드 구현
  Semo/Managers/CoreDataManager.swift
Labels: ✨ Feature

#118 [2022.10.06] hotfix/SongDetailViewSaveButton >> 저장버튼 활성화 조건 수정
  Semo/Views/SongDetail/SongDetailView.swift
Labels: :lady_beetle: Bug

#115 [2022.10.05] feat/AddSingingListUI >> 노래 리스트에서만 삭제하는 기능 추가
  Semo.xcodeproj/project.pbxproj
  Semo.xcodeproj/xcuserdata/jungin-yoo.xcuserdatad/xcschemes/xcschememanagement.plist
  Semo/Views/AllSongList/DeleteSongButtonView.swift
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/DeleteSingingListButtonView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingListDetail/DeleteFromSongToSingingListView.swift
  Semo/Views/SingingListDetail/SingingListDetailCellView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
  Semo/Views/SongDetail/SongInfoView.swift
Labels: :lady_beetle: Bug, ✨ Feature

#119 [2022.10.10] fix/singinglistSongCount >> 싱잉리스트에 들어있는 노래 개수 로직 수정
  NSManagedObject/SingingList+CoreDataClass.swift
  NSManagedObject/SingingList+CoreDataProperties.swift
  NSManagedObject/Song+CoreDataClass.swift
  NSManagedObject/Song+CoreDataProperties.swift
  Semo.xcdatamodeld/Semo.xcdatamodel/contents
  Semo.xcodeproj/project.pbxproj
  Semo.xcworkspace/contents.xcworkspacedata
  Semo/Managers/CoreDataManager.swift
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingList/SingingListSheet/SingingListSheetView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
Labels: ✨ Feature

#121 [2022.10.10] feat/singingListSheetView >> 노래에서 싱잉리스트 추가할때 이미 추가된 싱잉리스트는 체크되게 표시
  Semo/Views/SingingList/SingingListSheet/SingingListSheetView.swift
Labels: ✨ Feature

#123 [fix] #122 리스트 디테일 뷰에서 보이는 노래의 제목과 가수 왼쪽 정렬
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/SingingListDetail/SingingListDetailCellView.swift
  Semo/Views/SongDetail/SongInfoView.swift
Labels: ✨ Feature

#124 [2022.10.10] fix/launchScreen >> 런치 스크린 이미지 사이즈를 추가해줬습니다
  Semo/Assets.xcassets/LaunchScreenImage.imageset/Contents.json
  Semo/Assets.xcassets/LaunchScreenImage.imageset/LaunchScreenImage.png
  Semo/Assets.xcassets/LaunchScreenImage.imageset/LaunchScreenImage@2x.png
  Semo/Assets.xcassets/LaunchScreenImage.imageset/LaunchScreenImage@3x.png
  Semo/Assets.xcassets/OnboardingImage.imageset/Contents.json
  Semo/Info.plist
  Semo/Views/OnBoarding/OnBoardingView.swift
Labels: :lady_beetle: Bug

#127 [2022.10.29] feat/DeviceSize >> 메인뷰, 디테일뷰 기기대응
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/SingingListView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
  Semo/Views/SongDetail/LevelPickerView.swift
  Semo/Views/SongDetail/SongDetailView.swift
  Semo/Views/SongDetail/TunePickerView.swift
Labels: ✨ Feature
