Repository Za-DO/Semo, pull requests merged in 2022-09, with the labels that each got.

#55 [2022.08.14] hotfix/fixAddSongViews >> 디테일 UI 및 버튼 스타일 수정
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/Others/FinalConfirmButtonView.swift
  Semo/Views/SingingList/SingingListSheet/CheckboxToggleStyle.swift
  Semo/Views/SingingList/SingingListSheet/SingingListSheetView.swift
  Semo/Views/SingingListDetail/SingingListModalView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor

#57 [2022.08.15] Refactor/add song button >> ConfirmButtonVIew 리팩토링 및 뷰 상세 패딩값 조정
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/AddSong/AddSongView.swift
  Semo/Views/Others/ConfirmButtonView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor

#56 [2022.08.15] feat/addSongLogic >> 기본 노래 정보 추가 로직 구현, CoreData코드 모듈화
  Semo.xcodeproj/project.pbxproj
  Semo/Managers/CoreDataInitManager.swift
  Semo/Managers/CoreDataManager.swift
  Semo/Managers/TestManager.swift
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/AddSong/AddSongView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/SingingListSheet/SingingListSheetView.swift
  Semo/Views/SingingListDetail/SingingListModalView.swift
  Semo/Views/TestView.swift
Labels: :lady_beetle: Bug, ✨ Feature

#60 [hotfix] sheet disabled 버튼 에러 수정
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AddSong/AddSongView.swift
  Semo/Views/SingingList/SingingListSheet/SingingListSheetView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor

#63 [2022.09.14] feat/duplicateCheck >> CoreData에 데이터 저장시 중복검사, Song의 SingingLIst태그 삭제 로직
  Semo.xcodeproj/project.pbxproj
  Semo/Managers/CoreDataManager.swift
  Semo/Views/SingingList/SingingListSheet/SingingListSheetView.swift
  Semo/Views/SongDetail/SongDetailView.swift
Labels: ✨ Feature

#64 [2022.09.14] fix/addSong >> 노래 저장시 추가 정보 기본 설정
  Semo/Managers/CoreDataManager.swift
Labels: ✨ Feature

#65 [2022.09.14] feat/deleteSongView >> 편집 버튼 터치 시 삭제 버튼 나타나는 기능 구현
  Semo.xcodeproj/project.pbxproj
  Semo/Views/AllSongList/DeleteSongButtonView.swift
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingList/SingingListSheet/SingingListToggleView.swift
  Semo/Views/SingingList/SingingListView.swift
  Semo/Views/SingingListDetail/SingingListDetailCellView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
Labels: ✨ Feature

#69 [2022.09.14] fix/Refresh >> 뷰 리프레쉬 로직 변경
  Semo/Managers/CoreDataManager.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingList/SingingListView.swift
Labels: ✨ Feature

#70 Feat/edit song detail view
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/SongDetail/SongDetailView.swift
  Semo/Views/SongDetail/SongInfoView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor, ✨ Feature

#71 [2022.09.14] feat/coreDataLogic >> CoreData 메서드 구현
  Semo/Managers/CoreDataManager.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor, ✨ Feature

#75 Feat/customBackButton >> 커스텀 백버튼 생성 및 저장 alert 추가
  Semo.xcodeproj/project.pbxproj
  Semo/Views/AddSong/AddSongView.swift
  Semo/Views/MainView.swift
  Semo/Views/Others/CustomBackButton.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
  Semo/Views/SingingListDetail/SingingListModalView.swift
  Semo/Views/SongDetail/SongDetailView.swift
Labels: ✨ Feature

#81 [hotfix] AddSong 플로우에서 정보 저장하는 코드 수정
  Semo/Managers/CoreDataManager.swift
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/AddSong/AddSongView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor

#76 Feat/addDeleteSongFunction >> 노래 삭제 구현 및 편집 버튼 비활성화 코드 추가
  Semo.xcodeproj/project.pbxproj
  Semo.xcodeproj/xcuserdata/jungin-yoo.xcuserdatad/xcschemes/xcschememanagement.plist
  Semo/Managers/CoreDataManager.swift
  Semo/Views/AllSongList/DeleteSongButtonView.swift
  Semo/Views/AllSongList/SongEditButtonView.swift
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingList/DeleteSingingListButtonView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingList/SingingListView.swift
  Semo/Views/SingingListDetail/SingingListDetailCellView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
  Semo/Views/SongDetail/SongDetailView.swift
  Semo/Views/TabBar/TabBarView.swift
Labels: :lady_beetle: Bug, ✨ Feature

#84 [hotfix] merge 후 발생한 오류 해결
  Semo.xcodeproj/xcuserdata/jungin-yoo.xcuserdatad/xcschemes/xcschememanagement.plist
  Semo/Views/SingingListDetail/SingingListDetailView.swift
Labels: :lady_beetle: Bug

#90 Feat/add singing list edit view
  Semo/Extensions/ViewExtension.swift
  Semo/Views/MainView.swift
  Semo/Views/Others/TextFieldView.swift
  Semo/Views/SingingList/DeleteSingingListButtonView.swift
  Semo/Views/SingingList/SingingListCellView.swift
  Semo/Views/SingingList/SingingListView.swift
  Semo/Views/SingingListDetail/SingingListDetailCellView.swift
  Semo/Views/SingingListDetail/SingingListDetailView.swift
Labels: :lady_beetle: Bug, ✨ Feature

#92 [fix] #91 노래 추가후 메인뷰 동기화 && 네비게이션 핑퐁 현상 해결
  Semo/Views/AddSong/AddMoreInfoView.swift
  Semo/Views/AddSong/AddSingingListTagView.swift
  Semo/Views/AddSong/AddSongView.swift
  Semo/Views/AllSongList/SongListView.swift
  Semo/Views/MainView.swift
  Semo/Views/SingingListDetail/AddSongButtonView.swift
  Semo/Views/TabBar/TabBarView.swift
Labels: :lady_beetle: Bug, ⚒: Refactor

#93 feat/EditSongDetailView >> 저장된 노래 상세 정보 디테일뷰에서 보여주기, 노래 삭제 함수 디테일 뷰에 추가
  Semo/Views/AllSongList/SongListCellView.swift
  Semo/Views/SongDetail/SongDetailView.swift
Labels: ✨ Feature
